# Generated by Django 5.2.4 on 2026-03-16 16:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_output_output_type_alter_upload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.models.file_path),
        ),
    ]
